"""Create Video and Image tables

Revision ID: 1acad03f0b18
Revises: 24b5bbbf212b
Create Date: 2023-06-24 14:37:49.824521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base

# revision identifiers, used by Alembic.
revision = '1acad03f0b18'
down_revision = '24b5bbbf212b'
branch_labels = None
depends_on = None


Base = declarative_base()


class MovieData(Base):
    __tablename__ = 'movie_data'
    uuid = sa.Column(sa.UUID(as_uuid=True), primary_key=True,
                     unique=True, nullable=False)
    imdbid = sa.Column(sa.String(16), nullable=False, unique=True)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'movie_images',
        sa.Column('id', sa.Integer(), autoincrement=True, primary_key=True),
        sa.Column('aspect_ratio', sa.Float(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('iso_639_1', sa.String(length=2), nullable=True),
        sa.Column('file_path', sa.String(length=100), nullable=True),
        sa.Column('vote_average', sa.Float(), nullable=True),
        sa.Column('vote_count', sa.Integer(), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('movie_uuid', sa.UUID(as_uuid=True),
                  sa.ForeignKey('movie_data.uuid')),
        sa.Column('movie_imdbid', sa.String(16),
                  sa.ForeignKey('movie_data.imdbid')),
    )

    op.create_table(
        'movie_videos',
        sa.Column('id', sa.String(length=24), nullable=False),
        sa.Column('iso_639_1', sa.String(length=2), nullable=True),
        sa.Column('iso_3166_1', sa.String(length=2), nullable=True),
        sa.Column('name', sa.String(length=200), nullable=True),
        sa.Column('key', sa.String(length=200), nullable=True),
        sa.Column('site', sa.String(length=100), nullable=True),
        sa.Column('size', sa.Integer(), nullable=True),
        sa.Column('type', sa.String(length=200), nullable=True),
        sa.Column('official', sa.Boolean(), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('movie_uuid', sa.UUID(as_uuid=True),
                  sa.ForeignKey('movie_data.uuid')),
        sa.Column('movie_imdbid', sa.String(16),
                  sa.ForeignKey('movie_data.imdbid')),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    op.drop_table('movie_videos')
    op.drop_table('movie_images')
